### ISSUE TITLE
Polaris-sync architecture design（Welcome Discuss）

### ISSUE THREAD

**Issue by chuntaojun** [polarismesh/polaris-sync#2]
1. 前端选型的话，可以参考下：https://tdesign.tencent.com/starter/
2. 架构设计图待同步上传

**Comment by chuntaojun** [comment]
![截屏2021-12-29 下午12 48 45](https://user-images.githubusercontent.com/23445172/147628304-7f3afa7f-e2b4-4d9e-aa5e-67b3240936e1.png)

**Comment by andrewshan** [comment]
![image](https://user-images.githubusercontent.com/45474304/182141807-8f3fd7d4-87a5-40f7-8df1-c18c87e7d1be.png)

**Comment by andrewshan** [comment]
## 为什么要做polaris-sync

polaris-sync主要解决的是用户的2个使用场景：

- 服务注册中心的热迁移：用户服务需要从注册中心A迁移到注册中心B，在迁移过程中，注册到新老注册中心的服务可以支持相互发现及访问。
- 网关直通注册中心：后台服务数据注册在注册中心，外部请求通过网关直接接入后台服务。

###  服务注册中心的热迁移

服务注册中心热迁移，主要有2种方式实现，一种是客户端双注册双发现，另外一种服务端数据同步。

对于Java程序来说，客户端的双注册双发现可以通过java字节码agent的方式进行无侵入实现，如下图：
![image](https://user-images.githubusercontent.com/45474304/184838250-46b89903-0aed-4760-9d0f-2d69419f634c.png)

但是对于非Java应用，如果要实现双注册双发现的话，就需要对应用进行一定的侵入式修改，对用户来说不那么友好，因此，服务端数据同步可以解决这个问题，通过服务端进行双向数据同步，使得2个注册中心都有全量的数据，这样两边的服务都可以相互发现调用。

polaris-sync主要是用来解决服务端之间数据同步的问题，支持不同注册中心之间的数据同步，如下图：
![image](https://user-images.githubusercontent.com/45474304/184841051-ae4d2264-7491-4e6d-bd27-888b38a10a12.png)

#

**Comment by andrewshan** [comment]
## polaris-sync功能架构

![image](https://user-images.githubusercontent.com/45474304/184850615-8d97bf53-0a13-4c30-b0f0-10c0cdf3a6af.png)
